allowBuilds:
  bufferutil: true
  electron: true
  electron-winstaller: true
  esbuild: true
  unrs-resolver: true
  utf-8-validate: true
patchedDependencies:
  app-builder-lib@26.8.1: patches/app-builder-lib@26.8.1.patch
shamefullyHoist: true
